# Generated by Django 4.2.16 on 2024-10-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='cars/unavailable_image.jpg', null=True, upload_to='cars/'),
        ),
    ]
